import { QuizQuestion } from '@/types';

// Start date: May 18, 2026
export const INTERNSHIP_START_DATE = '2026-05-18';
export const ADMIN_EMAIL = 'likhithmanakala@gmail.com';

export const WEEKS = [
  { week_number: 1, title: 'Python Programming Fundamentals', domain: 'Python' },
  { week_number: 2, title: 'SQL & Database Concepts', domain: 'SQL' },
  { week_number: 3, title: 'Cloud Computing Essentials', domain: 'Cloud' },
  { week_number: 4, title: 'Machine Learning Basics', domain: 'ML' },
  { week_number: 5, title: 'Internet of Things (IoT)', domain: 'IoT' },
  { week_number: 6, title: 'Capstone Project Work', domain: 'Capstone' },
];

export const DAYS_TOPICS: { day: number; topic: string; description: string; resource_link?: string }[] = [
  { day: 1, topic: 'Data Foundations', description: 'In-depth session on Data Foundations: What is Data - Data Lifecycle - Basic Functions', resource_link: 'https://docs.google.com/presentation/d/1Kxky8zVZ0tuE-aIazOr2pSerVpxF7gBz/edit?usp=drive_link&ouid=110452534344800716911&rtpof=true&sd=true' },
  { day: 2, topic: 'Variables & Data Types', description: 'Understanding integers, floats, strings, booleans, and type casting.', resource_link: 'https://docs.google.com/presentation/d/1MiYCQX8vS8en9Lbndh5isLl71ilHzybS/edit?usp=drive_link&ouid=110452534344800716911&rtpof=true&sd=true' },
  { day: 3, topic: 'Control Flow', description: 'If-else statements, loops (for, while), and conditional expressions.', resource_link: 'https://docs.google.com/presentation/d/1iisDejlYzKKc_DMJnv1UBGY-5k9r4lDK/edit?usp=drive_link&ouid=110452534344800716911&rtpof=true&sd=true' },
  { day: 4, topic: 'Functions & Modules', description: 'Defining functions, parameters, return values, importing modules.' },
  { day: 5, topic: 'Data Structures', description: 'Lists, tuples, dictionaries, sets and their operations.' },
  { day: 6, topic: 'Introduction to SQL', description: 'Relational databases, SQL syntax, SELECT basics.' },
  { day: 7, topic: 'Filtering & Sorting', description: 'WHERE clause, ORDER BY, LIMIT, LIKE, and comparison operators.' },
  { day: 8, topic: 'Joins & Relationships', description: 'INNER JOIN, LEFT JOIN, RIGHT JOIN, table relationships.' },
  { day: 9, topic: 'Aggregation & Grouping', description: 'COUNT, SUM, AVG, MIN, MAX, GROUP BY, HAVING.' },
  { day: 10, topic: 'Advanced SQL', description: 'Subqueries, views, indexes, and transactions.' },
  { day: 11, topic: 'Cloud Computing Overview', description: 'IaaS, PaaS, SaaS models and major cloud providers.' },
  { day: 12, topic: 'AWS Fundamentals', description: 'EC2, S3, IAM — core AWS services overview.' },
  { day: 13, topic: 'Serverless & Functions', description: 'AWS Lambda, Azure Functions, event-driven architecture.' },
  { day: 14, topic: 'Cloud Databases', description: 'RDS, DynamoDB, Cloud SQL — managed database services.' },
  { day: 15, topic: 'Cloud Deployment', description: 'CI/CD pipelines, Docker basics, and cloud deployment strategies.' },
  { day: 16, topic: 'Intro to Machine Learning', description: 'What is ML, types of learning, the ML pipeline.' },
  { day: 17, topic: 'Data Preprocessing', description: 'Handling missing data, normalization, feature engineering.' },
  { day: 18, topic: 'Supervised Learning', description: 'Linear regression, logistic regression, decision trees.' },
  { day: 19, topic: 'Model Evaluation', description: 'Accuracy, precision, recall, F1-score, confusion matrix.' },
  { day: 20, topic: 'Unsupervised Learning', description: 'K-means clustering, PCA, anomaly detection.' },
  { day: 21, topic: 'IoT Fundamentals', description: 'Sensors, actuators, IoT architecture and protocols.' },
  { day: 22, topic: 'Arduino & Microcontrollers', description: 'Arduino basics, GPIO, reading sensor data.' },
  { day: 23, topic: 'IoT Communication', description: 'MQTT, HTTP, Bluetooth, WiFi protocols for IoT.' },
  { day: 24, topic: 'IoT Cloud Integration', description: 'Connecting devices to AWS IoT, data dashboards.' },
  { day: 25, topic: 'IoT Security', description: 'Encryption, authentication, secure firmware updates.' },
  { day: 26, topic: 'Project Planning', description: 'Defining scope, setting milestones, team coordination.' },
  { day: 27, topic: 'Development Sprint 1', description: 'Building core features of the capstone project.' },
  { day: 28, topic: 'Development Sprint 2', description: 'Integrating components, testing, and debugging.' },
  { day: 29, topic: 'Documentation & Testing', description: 'Writing documentation, unit tests, demo preparation.' },
  { day: 30, topic: 'Final Presentation', description: 'Project showcase, peer review, and feedback session.' },
];

export const QUIZ_QUESTIONS: Record<number, QuizQuestion[]> = {
  1: [
    { question: 'When do you use a .csv file?', options: ['For reports from data', 'For data analysis', 'For large scale data transfers', 'For data visualization'], correct_index: 1 },
    { question: 'What is Data?', options: ['A saved file', 'A set of images', 'Raw information', 'None'], correct_index: 2 },
    { question: 'Benefits of Excel?', options: ['Can show tables and reports', 'Can include diagrams', 'Reports can be editable', 'All of the above'], correct_index: 3 },
    { question: 'What is the primary role of data in an organization?', options: ['To generate reports automatically', 'To serve as the source of truth for decisions and actions', 'To replace human judgment entirely', 'To reduce the number of employees needed'], correct_index: 1 },
    { question: 'Which of the following is NOT listed as a method of data collection?', options: ['Surveys', 'Observations', 'Brainstorming', 'Machine learning models'], correct_index: 3 },
    { question: 'What does the \'progression of data\' refer to?', options: ['Data growing in file size over time', 'Raw data being refined according to end user requirements', 'Moving data from paper to digital formats', 'Archiving old data to free up storage'], correct_index: 1 },
    { question: 'Which file format is described as the most preferred for data that includes text figures and numbers?', options: ['.pdf', '.csv', '.txt', '.xlsx'], correct_index: 3 },
    { question: 'What is the maximum number of rows supported per sheet in Excel?', options: ['500000', '1000000', '1048576', '2097152'], correct_index: 2 },
    { question: 'What is a key difference between .xls and .xlsx?', options: ['.xls is newer and has better performance', '.xlsx is an older format compatible only with Word 97-2003', '.xlsx is lighter more compatible with modern platforms and has better security', '.xls supports more rows than .xlsx'], correct_index: 2 },
    { question: 'Why is .csv NOT recommended for analytical work?', options: ['It has a row limit of 100000', 'It does not support multiple sheets in a workbook', 'It cannot store numbers', 'It requires special software to open'], correct_index: 1 },
    { question: 'What is the main advantage of .pdf as a file format?', options: ['It supports macros and formulas', 'It allows easy editing on all platforms', 'It keeps content looking the same on all platforms without format changes', 'It can hold unlimited data'], correct_index: 2 },
    { question: 'Which of the following best describes the difference between .doc and .docx?', options: ['.doc is newer and has a smaller file size', '.docx is compatible with Word 97-2003 only', '.docx is an updated format that is lighter cross-platform compatible and more secure', '.doc and .docx are identical formats'], correct_index: 2 }
  ],
  2: [
    { question: 'What is the key difference between COUNT and COUNTA in Excel?', options: ['COUNT adds numbers; COUNTA adds text values', 'COUNT only counts numeric cells; COUNTA counts all non-empty cells regardless of type', 'COUNT works on rows only; COUNTA works on columns only', 'COUNT and COUNTA are identical – they do the same thing'], correct_index: 1 },
    { question: '=AVERAGE(F2:F23) is equivalent to which of the following formulas?', options: ['=SUM(F2:F23)/COUNT(F2:F23)', '=SUM(F2:F23)/22', '=COUNT(F2:F23)/22', '=SUM(F2+F23)/2'], correct_index: 0 },
    { question: 'Which pair of functions would you use to find the highest and lowest scores in a dataset?', options: ['UPPER and LOWER', 'COUNT and COUNTA', 'MAX and MIN', 'SUM and AVERAGE'], correct_index: 2 },
    { question: 'A student\'s name is stored as \'aRaV sInGh\'. Which function would convert it to \'Aarav Singh\'?', options: ['=UPPER(A1)', '=LOWER(A1)', '=PROPER(A1)', '=TRIM(A1)'], correct_index: 2 },
    { question: 'You enter a formula in cell B2 as =A1 and then copy it down to B3. What type of reference is A1 and what will B3 display?', options: ['A relative reference; B3 will show the value from A2', 'An absolute reference; B3 will show the value from A1', 'A mixed reference; B3 will show the value from A2', 'A mixed reference; B3 will show the value from A1'], correct_index: 0 },
    { question: 'You write =A1 in B2 with no dollar signs and copy it down to B3 B4 and B5. How will the reference change?', options: ['It is an absolute reference and will stay A1 in all rows', 'It is a relative reference and will adjust to A2 A3 A4', 'It is a mixed reference and will change only the column not the row', 'It is a mixed reference and will change to A$2 A$3 A$4'], correct_index: 1 },
    { question: 'What will =EDATE("01-Jan-2024" 3) return?', options: ['01-Jan-2027', '03-Jan-2024', '01-Apr-2024', '01-Mar-2024'], correct_index: 2 },
    { question: 'How is =NOW() different from =TODAY() in Excel?', options: ['NOW() returns only the time; TODAY() returns only the date', 'NOW() returns date + current time; TODAY() returns only the date', 'Both return the same result', 'NOW() is used for past dates and TODAY() for future dates'], correct_index: 1 },
    { question: 'What is the correct syntax of the CONCAT function in Excel?', options: ['=CONCAT(text1 text2 ...)', '=CONCAT(cell separator)', '=CONCAT(range delimiter)', '=CONCAT(string position length)'], correct_index: 0 },
    { question: 'Which of the following can visually identify duplicate values in a column using Conditional Formatting?', options: ['Data Bars', 'Highlight Duplicate option', 'Icon Sets', 'Color Scales'], correct_index: 1 },
    { question: 'How can you prevent any user from entering data into a protected Excel sheet?', options: ['By applying Conditional Formatting rules', 'By using the TRIM function on all cells', 'By protecting the sheet using the sheet protection feature', 'By converting the range into a table'], correct_index: 2 },
    { question: 'Which of the following is an advantage of using the \'Format as Table\' option in Excel?', options: ['It locks the sheet so no edits can be made', 'It automatically applies filters to headers and adjusts the table when rows or columns are added', 'It converts all text data into numbers', 'It merges all cells in the selected range'], correct_index: 1 }
  ],
  3: [
    { question: 'Which keyword starts a conditional statement?', options: ['for', 'while', 'if', 'switch'], correct_index: 2 },
    { question: 'What is the output of: for i in range(3): print(i)?', options: ['0 1 2', '1 2 3', '0 1 2 3', 'Error'], correct_index: 0 },
    { question: 'Which loop is best for unknown iterations?', options: ['for', 'while', 'do-while', 'foreach'], correct_index: 1 },
    { question: 'What does "break" do in a loop?', options: ['Skips iteration', 'Exits loop', 'Restarts loop', 'Pauses loop'], correct_index: 1 },
    { question: 'What does "continue" do?', options: ['Exits loop', 'Skips to next iteration', 'Restarts loop', 'Ends program'], correct_index: 1 },
    { question: 'What is the ternary operator in Python?', options: ['? :', 'if-else in one line', 'switch-case', '&&'], correct_index: 1 },
    { question: 'How many times does range(1, 5) iterate?', options: ['5', '4', '3', '6'], correct_index: 1 },
    { question: 'What keyword handles exceptions?', options: ['catch', 'try', 'except', 'try-except'], correct_index: 3 },
    { question: 'What is "elif" short for?', options: ['else-if', 'elif', 'elseif', 'else if'], correct_index: 0 },
    { question: 'What does pass do?', options: ['Exits function', 'Nothing', 'Skips line', 'Returns None'], correct_index: 1 },
  ],
  4: [
    { question: 'Which keyword defines a function?', options: ['function', 'func', 'def', 'define'], correct_index: 2 },
    { question: 'What does return do?', options: ['Prints value', 'Sends value back', 'Exits program', 'Logs value'], correct_index: 1 },
    { question: 'What are *args used for?', options: ['Keyword args', 'Variable positional args', 'Default args', 'Named args'], correct_index: 1 },
    { question: 'What are **kwargs used for?', options: ['Variable keyword args', 'Positional args', 'List args', 'Tuple args'], correct_index: 0 },
    { question: 'What is a lambda function?', options: ['Named function', 'Anonymous function', 'Class method', 'Generator'], correct_index: 1 },
    { question: 'How do you import a module?', options: ['include math', 'import math', 'require math', '#include math'], correct_index: 1 },
    { question: 'What is __init__ in a class?', options: ['Destructor', 'Constructor', 'Iterator', 'Generator'], correct_index: 1 },
    { question: 'What does len() return?', options: ['Type', 'Length', 'Size in bytes', 'Index'], correct_index: 1 },
    { question: 'What is a docstring?', options: ['Comment', 'Documentation string', 'Variable', 'Error message'], correct_index: 1 },
    { question: 'Which is a built-in module?', options: ['numpy', 'pandas', 'os', 'flask'], correct_index: 2 },
  ],
  5: [
    { question: 'Which method adds to end of list?', options: ['add()', 'insert()', 'append()', 'push()'], correct_index: 2 },
    { question: 'How to access dict value?', options: ['dict[key]', 'dict.key', 'dict(key)', 'dict->key'], correct_index: 0 },
    { question: 'What is a set?', options: ['Ordered duplicates', 'Unordered unique', 'Ordered unique', 'Key-value pairs'], correct_index: 1 },
    { question: 'How to get list length?', options: ['list.size()', 'len(list)', 'list.length', 'count(list)'], correct_index: 1 },
    { question: 'What does pop() do on a list?', options: ['Adds element', 'Removes last', 'Sorts list', 'Reverses list'], correct_index: 1 },
    { question: 'Which creates an empty dict?', options: ['[]', '()', '{}', 'dict[]'], correct_index: 2 },
    { question: 'What is list slicing syntax?', options: ['list(1,3)', 'list[1:3]', 'list.slice(1,3)', 'list{1:3}'], correct_index: 1 },
    { question: 'Tuples are defined with?', options: ['[]', '()', '{}', '<>'], correct_index: 1 },
    { question: 'How to check key in dict?', options: ['key in dict', 'dict.has(key)', 'dict.contains(key)', 'key exists dict'], correct_index: 0 },
    { question: 'What does sorted() return?', options: ['None', 'New sorted list', 'Same list sorted', 'Iterator'], correct_index: 1 },
  ],
  6: [
    { question: 'What does SQL stand for?', options: ['Structured Query Language', 'Simple Query Logic', 'Standard Query Language', 'Sequential Query List'], correct_index: 0 },
    { question: 'Which command retrieves data?', options: ['GET', 'FETCH', 'SELECT', 'RETRIEVE'], correct_index: 2 },
    { question: 'Which clause filters rows?', options: ['FILTER', 'WHERE', 'HAVING', 'LIMIT'], correct_index: 1 },
    { question: 'What is a PRIMARY KEY?', options: ['Any column', 'Unique identifier', 'Foreign reference', 'Index'], correct_index: 1 },
    { question: 'Which creates a table?', options: ['MAKE TABLE', 'NEW TABLE', 'CREATE TABLE', 'ADD TABLE'], correct_index: 2 },
    { question: 'Which deletes all rows?', options: ['DELETE', 'DROP', 'TRUNCATE', 'REMOVE'], correct_index: 2 },
    { question: 'What is NULL?', options: ['Zero', 'Empty string', 'Unknown value', 'False'], correct_index: 2 },
    { question: 'INSERT INTO adds what?', options: ['Column', 'Table', 'Row', 'Database'], correct_index: 2 },
    { question: 'Which keyword removes duplicates?', options: ['UNIQUE', 'DISTINCT', 'DIFFERENT', 'SINGLE'], correct_index: 1 },
    { question: 'What does * mean in SELECT *?', options: ['Multiply', 'All columns', 'First column', 'Count'], correct_index: 1 },
  ],
};

export const TASKS_DATA: { day: number; title: string; description: string }[] = [
  { day: 1, title: 'Python Setup & Hello World', description: 'Install Python, set up VS Code, and write a Hello World program.' },
  { day: 3, title: 'Control Flow Exercises', description: 'Solve 5 control flow problems using if-else and loops.' },
  { day: 5, title: 'Data Structures Project', description: 'Build a contact book using dictionaries and lists.' },
  { day: 8, title: 'SQL Joins Practice', description: 'Write queries using different types of joins on sample tables.' },
  { day: 10, title: 'Database Design', description: 'Design a normalized database schema for a library system.' },
  { day: 13, title: 'Serverless Function', description: 'Deploy a simple serverless function on any cloud platform.' },
  { day: 15, title: 'Docker Container', description: 'Containerize a simple Python app using Docker.' },
  { day: 18, title: 'ML Model Training', description: 'Train a linear regression model on a sample dataset.' },
  { day: 20, title: 'Clustering Analysis', description: 'Apply K-means clustering on a real-world dataset.' },
  { day: 23, title: 'IoT Communication Demo', description: 'Set up MQTT communication between two devices.' },
  { day: 25, title: 'IoT Security Report', description: 'Write a report on IoT security best practices.' },
  { day: 30, title: 'Capstone Final Submission', description: 'Submit your completed capstone project with documentation.' },
];
