import { QuizQuestion } from '@/types';

// Start date: May 18, 2026
export const INTERNSHIP_START_DATE = '2026-05-18';
export const ADMIN_EMAIL = 'likhithmanakala@gmail.com';

export const WEEKS = [
  { week_number: 1, title: 'Python Programming Fundamentals', domain: 'Python' },
  { week_number: 2, title: 'SQL & Database Concepts', domain: 'SQL' },
  { week_number: 3, title: 'Cloud Computing Essentials', domain: 'Cloud' },
  { week_number: 4, title: 'Machine Learning Basics', domain: 'ML' },
  { week_number: 5, title: 'Internet of Things (IoT)', domain: 'IoT' },
  { week_number: 6, title: 'Capstone Project Work', domain: 'Capstone' },
];

export const DAYS_TOPICS: { day: number; topic: string; description: string }[] = [
  { day: 1, topic: 'Introduction to Python', description: 'Setting up Python environment, basic syntax, and first program.' },
  { day: 2, topic: 'Variables & Data Types', description: 'Understanding integers, floats, strings, booleans, and type casting.' },
  { day: 3, topic: 'Control Flow', description: 'If-else statements, loops (for, while), and conditional expressions.' },
  { day: 4, topic: 'Functions & Modules', description: 'Defining functions, parameters, return values, importing modules.' },
  { day: 5, topic: 'Data Structures', description: 'Lists, tuples, dictionaries, sets and their operations.' },
  { day: 6, topic: 'Introduction to SQL', description: 'Relational databases, SQL syntax, SELECT basics.' },
  { day: 7, topic: 'Filtering & Sorting', description: 'WHERE clause, ORDER BY, LIMIT, LIKE, and comparison operators.' },
  { day: 8, topic: 'Joins & Relationships', description: 'INNER JOIN, LEFT JOIN, RIGHT JOIN, table relationships.' },
  { day: 9, topic: 'Aggregation & Grouping', description: 'COUNT, SUM, AVG, MIN, MAX, GROUP BY, HAVING.' },
  { day: 10, topic: 'Advanced SQL', description: 'Subqueries, views, indexes, and transactions.' },
  { day: 11, topic: 'Cloud Computing Overview', description: 'IaaS, PaaS, SaaS models and major cloud providers.' },
  { day: 12, topic: 'AWS Fundamentals', description: 'EC2, S3, IAM — core AWS services overview.' },
  { day: 13, topic: 'Serverless & Functions', description: 'AWS Lambda, Azure Functions, event-driven architecture.' },
  { day: 14, topic: 'Cloud Databases', description: 'RDS, DynamoDB, Cloud SQL — managed database services.' },
  { day: 15, topic: 'Cloud Deployment', description: 'CI/CD pipelines, Docker basics, and cloud deployment strategies.' },
  { day: 16, topic: 'Intro to Machine Learning', description: 'What is ML, types of learning, the ML pipeline.' },
  { day: 17, topic: 'Data Preprocessing', description: 'Handling missing data, normalization, feature engineering.' },
  { day: 18, topic: 'Supervised Learning', description: 'Linear regression, logistic regression, decision trees.' },
  { day: 19, topic: 'Model Evaluation', description: 'Accuracy, precision, recall, F1-score, confusion matrix.' },
  { day: 20, topic: 'Unsupervised Learning', description: 'K-means clustering, PCA, anomaly detection.' },
  { day: 21, topic: 'IoT Fundamentals', description: 'Sensors, actuators, IoT architecture and protocols.' },
  { day: 22, topic: 'Arduino & Microcontrollers', description: 'Arduino basics, GPIO, reading sensor data.' },
  { day: 23, topic: 'IoT Communication', description: 'MQTT, HTTP, Bluetooth, WiFi protocols for IoT.' },
  { day: 24, topic: 'IoT Cloud Integration', description: 'Connecting devices to AWS IoT, data dashboards.' },
  { day: 25, topic: 'IoT Security', description: 'Encryption, authentication, secure firmware updates.' },
  { day: 26, topic: 'Project Planning', description: 'Defining scope, setting milestones, team coordination.' },
  { day: 27, topic: 'Development Sprint 1', description: 'Building core features of the capstone project.' },
  { day: 28, topic: 'Development Sprint 2', description: 'Integrating components, testing, and debugging.' },
  { day: 29, topic: 'Documentation & Testing', description: 'Writing documentation, unit tests, demo preparation.' },
  { day: 30, topic: 'Final Presentation', description: 'Project showcase, peer review, and feedback session.' },
];

export const QUIZ_QUESTIONS: Record<number, QuizQuestion[]> = {
  1: [
    { question: 'What is the correct file extension for Python files?', options: ['.py', '.python', '.pt', '.pyt'], correct_index: 0 },
    { question: 'Which function is used to display output in Python?', options: ['echo()', 'console.log()', 'print()', 'display()'], correct_index: 2 },
    { question: 'Who created Python?', options: ['James Gosling', 'Guido van Rossum', 'Dennis Ritchie', 'Bjarne Stroustrup'], correct_index: 1 },
    { question: 'What symbol is used for single-line comments in Python?', options: ['//', '/*', '#', '--'], correct_index: 2 },
    { question: 'Which of the following is NOT a valid Python identifier?', options: ['_var', 'var1', '1var', 'Var'], correct_index: 2 },
    { question: 'What is Python primarily known as?', options: ['Compiled language', 'Interpreted language', 'Assembly language', 'Markup language'], correct_index: 1 },
    { question: 'Which command installs packages in Python?', options: ['npm install', 'pip install', 'apt-get', 'brew install'], correct_index: 1 },
    { question: 'What does PEP stand for?', options: ['Python Enhancement Proposal', 'Python Execution Protocol', 'Program Extension Pack', 'Python Entry Point'], correct_index: 0 },
    { question: 'Which Python version introduced f-strings?', options: ['2.7', '3.0', '3.6', '3.10'], correct_index: 2 },
    { question: 'What is the output of print(type(42))?', options: ['<class \'float\'>', '<class \'int\'>', '<class \'str\'>', '<class \'num\'>'], correct_index: 1 },
  ],
  2: [
    { question: 'Which is NOT a Python data type?', options: ['int', 'float', 'char', 'str'], correct_index: 2 },
    { question: 'What does int("42") return?', options: ['42', '"42"', 'Error', '4.2'], correct_index: 0 },
    { question: 'Which is a mutable data type?', options: ['tuple', 'string', 'list', 'frozenset'], correct_index: 2 },
    { question: 'What is the result of 10 / 3 in Python 3?', options: ['3', '3.33', '3.3333333333333335', 'Error'], correct_index: 2 },
    { question: 'How do you create a multi-line string?', options: ['Using \\n', 'Triple quotes', 'Semicolons', 'Backslash'], correct_index: 1 },
    { question: 'What is the default value of a boolean variable?', options: ['True', 'False', 'None', '0'], correct_index: 1 },
    { question: 'Which operator performs floor division?', options: ['/', '//', '%', '**'], correct_index: 1 },
    { question: 'What does str(100) return?', options: ['100', '"100"', '1.0', 'Error'], correct_index: 1 },
    { question: 'What is type(3.14)?', options: ['int', 'double', 'float', 'decimal'], correct_index: 2 },
    { question: 'Which is immutable?', options: ['list', 'dict', 'set', 'tuple'], correct_index: 3 },
  ],
  3: [
    { question: 'Which keyword starts a conditional statement?', options: ['for', 'while', 'if', 'switch'], correct_index: 2 },
    { question: 'What is the output of: for i in range(3): print(i)?', options: ['0 1 2', '1 2 3', '0 1 2 3', 'Error'], correct_index: 0 },
    { question: 'Which loop is best for unknown iterations?', options: ['for', 'while', 'do-while', 'foreach'], correct_index: 1 },
    { question: 'What does "break" do in a loop?', options: ['Skips iteration', 'Exits loop', 'Restarts loop', 'Pauses loop'], correct_index: 1 },
    { question: 'What does "continue" do?', options: ['Exits loop', 'Skips to next iteration', 'Restarts loop', 'Ends program'], correct_index: 1 },
    { question: 'What is the ternary operator in Python?', options: ['? :', 'if-else in one line', 'switch-case', '&&'], correct_index: 1 },
    { question: 'How many times does range(1, 5) iterate?', options: ['5', '4', '3', '6'], correct_index: 1 },
    { question: 'What keyword handles exceptions?', options: ['catch', 'try', 'except', 'try-except'], correct_index: 3 },
    { question: 'What is "elif" short for?', options: ['else-if', 'elif', 'elseif', 'else if'], correct_index: 0 },
    { question: 'What does pass do?', options: ['Exits function', 'Nothing', 'Skips line', 'Returns None'], correct_index: 1 },
  ],
  4: [
    { question: 'Which keyword defines a function?', options: ['function', 'func', 'def', 'define'], correct_index: 2 },
    { question: 'What does return do?', options: ['Prints value', 'Sends value back', 'Exits program', 'Logs value'], correct_index: 1 },
    { question: 'What are *args used for?', options: ['Keyword args', 'Variable positional args', 'Default args', 'Named args'], correct_index: 1 },
    { question: 'What are **kwargs used for?', options: ['Variable keyword args', 'Positional args', 'List args', 'Tuple args'], correct_index: 0 },
    { question: 'What is a lambda function?', options: ['Named function', 'Anonymous function', 'Class method', 'Generator'], correct_index: 1 },
    { question: 'How do you import a module?', options: ['include math', 'import math', 'require math', '#include math'], correct_index: 1 },
    { question: 'What is __init__ in a class?', options: ['Destructor', 'Constructor', 'Iterator', 'Generator'], correct_index: 1 },
    { question: 'What does len() return?', options: ['Type', 'Length', 'Size in bytes', 'Index'], correct_index: 1 },
    { question: 'What is a docstring?', options: ['Comment', 'Documentation string', 'Variable', 'Error message'], correct_index: 1 },
    { question: 'Which is a built-in module?', options: ['numpy', 'pandas', 'os', 'flask'], correct_index: 2 },
  ],
  5: [
    { question: 'Which method adds to end of list?', options: ['add()', 'insert()', 'append()', 'push()'], correct_index: 2 },
    { question: 'How to access dict value?', options: ['dict[key]', 'dict.key', 'dict(key)', 'dict->key'], correct_index: 0 },
    { question: 'What is a set?', options: ['Ordered duplicates', 'Unordered unique', 'Ordered unique', 'Key-value pairs'], correct_index: 1 },
    { question: 'How to get list length?', options: ['list.size()', 'len(list)', 'list.length', 'count(list)'], correct_index: 1 },
    { question: 'What does pop() do on a list?', options: ['Adds element', 'Removes last', 'Sorts list', 'Reverses list'], correct_index: 1 },
    { question: 'Which creates an empty dict?', options: ['[]', '()', '{}', 'dict[]'], correct_index: 2 },
    { question: 'What is list slicing syntax?', options: ['list(1,3)', 'list[1:3]', 'list.slice(1,3)', 'list{1:3}'], correct_index: 1 },
    { question: 'Tuples are defined with?', options: ['[]', '()', '{}', '<>'], correct_index: 1 },
    { question: 'How to check key in dict?', options: ['key in dict', 'dict.has(key)', 'dict.contains(key)', 'key exists dict'], correct_index: 0 },
    { question: 'What does sorted() return?', options: ['None', 'New sorted list', 'Same list sorted', 'Iterator'], correct_index: 1 },
  ],
  6: [
    { question: 'What does SQL stand for?', options: ['Structured Query Language', 'Simple Query Logic', 'Standard Query Language', 'Sequential Query List'], correct_index: 0 },
    { question: 'Which command retrieves data?', options: ['GET', 'FETCH', 'SELECT', 'RETRIEVE'], correct_index: 2 },
    { question: 'Which clause filters rows?', options: ['FILTER', 'WHERE', 'HAVING', 'LIMIT'], correct_index: 1 },
    { question: 'What is a PRIMARY KEY?', options: ['Any column', 'Unique identifier', 'Foreign reference', 'Index'], correct_index: 1 },
    { question: 'Which creates a table?', options: ['MAKE TABLE', 'NEW TABLE', 'CREATE TABLE', 'ADD TABLE'], correct_index: 2 },
    { question: 'Which deletes all rows?', options: ['DELETE', 'DROP', 'TRUNCATE', 'REMOVE'], correct_index: 2 },
    { question: 'What is NULL?', options: ['Zero', 'Empty string', 'Unknown value', 'False'], correct_index: 2 },
    { question: 'INSERT INTO adds what?', options: ['Column', 'Table', 'Row', 'Database'], correct_index: 2 },
    { question: 'Which keyword removes duplicates?', options: ['UNIQUE', 'DISTINCT', 'DIFFERENT', 'SINGLE'], correct_index: 1 },
    { question: 'What does * mean in SELECT *?', options: ['Multiply', 'All columns', 'First column', 'Count'], correct_index: 1 },
  ],
};

export const TASKS_DATA: { day: number; title: string; description: string }[] = [
  { day: 1, title: 'Python Setup & Hello World', description: 'Install Python, set up VS Code, and write a Hello World program.' },
  { day: 3, title: 'Control Flow Exercises', description: 'Solve 5 control flow problems using if-else and loops.' },
  { day: 5, title: 'Data Structures Project', description: 'Build a contact book using dictionaries and lists.' },
  { day: 8, title: 'SQL Joins Practice', description: 'Write queries using different types of joins on sample tables.' },
  { day: 10, title: 'Database Design', description: 'Design a normalized database schema for a library system.' },
  { day: 13, title: 'Serverless Function', description: 'Deploy a simple serverless function on any cloud platform.' },
  { day: 15, title: 'Docker Container', description: 'Containerize a simple Python app using Docker.' },
  { day: 18, title: 'ML Model Training', description: 'Train a linear regression model on a sample dataset.' },
  { day: 20, title: 'Clustering Analysis', description: 'Apply K-means clustering on a real-world dataset.' },
  { day: 23, title: 'IoT Communication Demo', description: 'Set up MQTT communication between two devices.' },
  { day: 25, title: 'IoT Security Report', description: 'Write a report on IoT security best practices.' },
  { day: 30, title: 'Capstone Final Submission', description: 'Submit your completed capstone project with documentation.' },
];
